#
cmake_minimum_required(VERSION 3.5)
project("RecluseRenderApi")

set (RECLUSE_RENDER_API_NAME "RecluseRenderApi")
set (RECLUSE_RENDER_API_MINOR 0)
set (RECLUSE_RENDER_API_MAJOR 0)
set (RECLUSE_RENDER_API_PATCH 0)

set (RECLUSE_VERSION_STRING "v${RECLUSE_RENDER_API_MAJOR}.${RECLUSE_RENDER_API_MINOR}.${RECLUSE_RENDER_API_PATCH}")

set (RECLUSE_INCLUDE_PATH ${CMAKE_SOURCE_DIR}/Include)
set (RECLUSE_SOURCE_PATH  ${CMAKE_SOURCE_DIR}/Source)
set (RECLUSE_INCLUDE_INTERNAL_PATH ${RECLUSE_INCLUDE_PATH}/Recluse/RenderApi)

set (RECLUSE_RENDER_API_FILES )
set (RECLUSE_RENDER_API_INCLUDES ${RECLUSE_INCLUDE_PATH})
set (RECLUSE_RENDER_API_LIBS )

option(ENABLE_TESTS "Builds Unit tests for the framework" OFF)

set (RECLUSE_FRAMEWORK_PATH "" CACHE STRING "Path/To/Framework")
set (RECLUSE_FRAMEWORK_BUILD_PATH "" CACHE STRING "Path/To/Framework/Build")

include (${CMAKE_CURRENT_SOURCE_DIR}/CMake/Common.cmake)
include (${RECLUSE_FRAMEWORK_PATH}/Build/CMake/GenerateExports.cmake)

add_library(${RECLUSE_RENDER_API_NAME} SHARED ${RECLUSE_RENDER_API_FILES})
target_include_directories(${RECLUSE_RENDER_API_NAME} PUBLIC ${RECLUSE_RENDER_API_INCLUDES} 
	${RECLUSE_FRAMEWORK_PATH}/Include
	${RECLUSE_FRAMEWORK_BUILD_PATH}/Include/RecluseFramework)
target_link_libraries(${RECLUSE_RENDER_API_NAME} ${RECLUSE_RENDER_API_LIBS} ${RECLUSE_FRAMEWORK_BUILD_PATH}/Lib/RecluseFramework.lib)

# Mirror the physical folder structure starting from the source directory
source_group(TREE "${CMAKE_CURRENT_SOURCE_DIR}" FILES ${RECLUSE_RENDER_API_FILES})

ExportThisLibrary(${RECLUSE_RENDER_API_NAME} ${CMAKE_CURRENT_SOURCE_DIR}/Recluse/Build)

if (ENABLE_TESTS)
	add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/Test)
endif()