
set ( RECLUSE_COMMON_HEADER_FILES ${RECLUSE_COMMON_HEADER_FILES}
	${RECLUSE_INCLUDE_INTERNAL_PATH}/Adapter.hpp
	${RECLUSE_INCLUDE_INTERNAL_PATH}/CommandList.hpp
	${RECLUSE_INCLUDE_INTERNAL_PATH}/Common.hpp
	${RECLUSE_INCLUDE_INTERNAL_PATH}/Device.hpp
	${RECLUSE_INCLUDE_INTERNAL_PATH}/Pipeline.hpp
	${RECLUSE_INCLUDE_INTERNAL_PATH}/Queue.hpp
	${RECLUSE_INCLUDE_INTERNAL_PATH}/Resource.hpp
	${RECLUSE_INCLUDE_INTERNAL_PATH}/Swapchain.hpp
	${RECLUSE_INCLUDE_INTERNAL_PATH}/Context.hpp
	)
	
set ( RECLUSE_COMMON_SOURCE_FILES ${RECLUSE_COMMON_SOURCE_FILES} 
	${RECLUSE_SOURCE_PATH}/DeviceCreator.cpp
	${RECLUSE_SOURCE_PATH}/CommandList.cpp
	${RECLUSE_SOURCE_PATH}/Queue.cpp
	${RECLUSE_SOURCE_PATH}/Shared/CommandOps.hpp
	)
	
set (RECLUSE_RENDER_API_FILES ${RECLUSE_RENDER_API_FILES} ${RECLUSE_COMMON_HEADER_FILES} ${RECLUSE_COMMON_SOURCE_FILES})