
set ( RECLUSE_COMMON_HEADER_FILES ${RECLUSE_COMMON_HEADER_FILES}
	${RECLUSE_INCLUDE_PATH}/RenderAdapter.hpp
	${RECLUSE_INCLUDE_PATH}/RenderCommandList.hpp
	${RECLUSE_INCLUDE_PATH}/RenderCommon.hpp
	${RECLUSE_INCLUDE_PATH}/RenderDevice.hpp
	${RECLUSE_INCLUDE_PATH}/RenderPipeline.hpp
	${RECLUSE_INCLUDE_PATH}/RenderQueue.hpp
	${RECLUSE_INCLUDE_PATH}/RenderResource.hpp
	${RECLUSE_INCLUDE_PATH}/RenderSwapchain.hpp
	${RECLUSE_INCLUDE_PATH}/RenderInstance.hpp
	)
	
set ( RECLUSE_COMMON_SOURCE_FILES ${RECLUSE_COMMON_SOURCE_FILES} 
	${RECLUSE_SOURCE_PATH}/DeviceCreator.cpp
	${RECLUSE_SOURCE_PATH}/RenderCommandList.cpp
	${RECLUSE_SOURCE_PATH}/RenderQueue.cpp
	${RECLUSE_SOURCE_PATH}/CommandOps.hpp
	)
	
set (RECLUSE_RENDER_API_FILES ${RECLUSE_RENDER_API_FILES} ${RECLUSE_COMMON_HEADER_FILES} ${RECLUSE_COMMON_SOURCE_FILES})