cmake_minimum_required(VERSION 3.16)
project("RecluseVulkan")

find_package(Vulkan REQUIRED)

set(RECLUSE_VULKAN_NAME "RecluseVulkan")

set(RECLUSE_VULKAN_PATH ${CMAKE_CURRENT_SOURCE_DIR})

set(RECLUSE_VULKAN_FILES 
	${RECLUSE_VULKAN_PATH}/VulkanCommon.hpp
	${RECLUSE_VULKAN_PATH}/VulkanCommon.cpp
	${RECLUSE_VULKAN_PATH}/SupportGraph.hpp
	${RECLUSE_VULKAN_PATH}/SupportGraph.cpp
	${RECLUSE_VULKAN_PATH}/VulkanDevice.hpp
	${RECLUSE_VULKAN_PATH}/VulkanDevice.cpp
	${RECLUSE_VULKAN_PATH}/VulkanContext.hpp
	${RECLUSE_VULKAN_PATH}/VulkanContext.cpp
	${RECLUSE_VULKAN_PATH}/VulkanAdapter.hpp
	${RECLUSE_VULKAN_PATH}/VulkanAdapter.cpp
	${RECLUSE_VULKAN_PATH}/VulkanInstance.hpp
	${RECLUSE_VULKAN_PATH}/VulkanInstance.cpp)
	
set(RECLUSE_VULKAN_INCLUDE_PATHS)
set(RECLUSE_VULKAN_LIB_PATHS)

if (${Vulkan_FOUND})
	add_library(${RECLUSE_VULKAN_NAME} SHARED ${RECLUSE_VULKAN_FILES})
	target_include_directories(${RECLUSE_VULKAN_NAME} PRIVATE 
		${Vulkan_INCLUDE_DIRS}
		${CMAKE_SOURCE_DIR}/Include
		${RECLUSE_FRAMEWORK_PATH}/Include
		${CMAKE_SOURCE_DIR}/Source
		${RECLUSE_FRAMEWORK_BUILD_PATH}/Include/RecluseFramework
		${RECLUSE_BUILD_PATH}/Include/RecluseRenderApi)
	target_link_libraries(${RECLUSE_VULKAN_NAME} PRIVATE Vulkan::Vulkan
		${RECLUSE_FRAMEWORK_BUILD_PATH}/Lib/RecluseFramework.lib
		${RECLUSE_RENDER_API_NAME})
	add_dependencies(${RECLUSE_VULKAN_NAME} ${RECLUSE_RENDER_API_NAME})
		
	install(TARGETS ${RECLUSE_VULKAN_NAME}
			CONFIGURATIONS Debug
			RUNTIME DESTINATION ${RECLUSE_BUILD_PATH}/Bin)
	install(TARGETS ${RECLUSE_VULKAN_NAME}
			CONFIGURATIONS Release
			RUNTIME DESTINATION ${RECLUSE_BUILD_PATH}/Bin)
	install(TARGETS ${RECLUSE_VULKAN_NAME}
			CONFIGURATIONS Debug
			ARCHIVE DESTINATION ${RECLUSE_BUILD_PATH}/Lib)
	install(TARGETS ${RECLUSE_VULKAN_NAME}
			CONFIGURATIONS Release
			ARCHIVE DESTINATION ${RECLUSE_BUILD_PATH}/Lib)
endif()